test:
  adapter: postgres
  database: ar-ex_test
  encoding: unicode
  host: localhost

development:
  adapter: postgres
  database: ar-ex_dev
  encoding: unicode
  host: localhost

production:
  adapter: postgres
  database: ar-ex_prod
  encoding: unicode
  host: localhost
